<?php

if( function_exists('acf_add_options_page') ) {

    acf_add_options_page(array(
        'page_title' => 'Ajustes del Tema',
        'menu_title' => 'Ajustes del Tema',
        'menu_slug' => 'ajustesTema',
        'capability' => 'edit_posts',
        'redirect' => false
    ));
    
    acf_add_options_sub_page(array(
        'page_title' => 'Ajustes de Header',
        'menu_title' => 'Ajustes de Header',
        'parent_slug' => 'ajustesTema',
    ));
}

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_673b3727eb3c4',
	'title' => 'Bloques de home',
	'fields' => array(
		array(
			'key' => 'field_673b3a5b5d83c',
			'label' => 'Secciones Home',
			'name' => 'seccionesHome',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_673c7ad3750fb' => array(
					'key' => 'layout_673c7ad3750fb',
					'name' => 'formulario',
					'label' => 'Formulario',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673c7aa61291e',
							'label' => 'Formulario',
							'name' => 'formulario',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_673c7aa612920',
									'label' => 'Título',
									'name' => 'titulo',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_673c7aa612921',
									'label' => 'Subtitulo',
									'name' => 'subtitulo',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_673c7aa612922',
									'label' => 'Lista de servicios',
									'name' => 'listaServicios',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'pagination' => 0,
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => 'Agregar Fila',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_673c7aa612923',
											'label' => 'Título',
											'name' => 'titulo',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_673c7aa612922',
										),
									),
								),
								array(
									'key' => 'field_673c7aa612925',
									'label' => 'Datos Formulario',
									'name' => 'datosFormulario',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 1,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c7b603ce32' => array(
					'key' => 'layout_673c7b603ce32',
					'name' => 'servicios',
					'label' => 'Servicios',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673c812a48d76',
							'label' => 'Encabezado',
							'name' => 'encabezado',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_673b3adf5d83e',
							'label' => 'Servicios',
							'name' => 'servicios',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Agregar Fila',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_673c39cae8db2',
									'label' => 'Imagen',
									'name' => 'imagen',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_673b3adf5d83e',
								),
								array(
									'key' => 'field_673c3965e8daf',
									'label' => 'Título',
									'name' => 'titulo',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_673b3adf5d83e',
								),
								array(
									'key' => 'field_673c39dbe8db3',
									'label' => 'Descripción',
									'name' => 'descripcion',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_673b3adf5d83e',
								),
								array(
									'key' => 'field_673c39efe8db4',
									'label' => 'Link',
									'name' => 'link',
									'aria-label' => '',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 'Saber más',
									'allow_in_bindings' => 1,
									'placeholder' => '',
									'parent_repeater' => 'field_673b3adf5d83e',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c800c902e6' => array(
					'key' => 'layout_673c800c902e6',
					'name' => 'nosotros',
					'label' => 'Nosotros',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673b3b3abac94',
							'label' => 'Nosotros',
							'name' => 'nosotros',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_673c3b9721412',
									'label' => 'Título',
									'name' => 'titulo',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_673c3bd121415',
									'label' => 'Texto',
									'name' => '',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 1,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c7ff7902e4' => array(
					'key' => 'layout_673c7ff7902e4',
					'name' => 'profesionales',
					'label' => 'Profesionales',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673b3b3cbac95',
							'label' => 'Profesionales',
							'name' => 'profesionales',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_673c3ca64db60',
									'label' => 'Imagen',
									'name' => 'imagen',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
								),
								array(
									'key' => 'field_673c3cc64db61',
									'label' => 'Nombre',
									'name' => 'nombre',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_673c3cde4db62',
									'label' => 'Especialidad',
									'name' => 'especialidad',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_673c3ce64db63',
									'label' => 'Descripción',
									'name' => 'descripcion',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 1,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c80ec09a8b' => array(
					'key' => 'layout_673c80ec09a8b',
					'name' => 'bannerPresupuesto',
					'label' => 'Banner Presupuesto',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673b3b41bac96',
							'label' => 'Mensaje',
							'name' => 'mensaje',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_673c90204b756',
							'label' => 'BotónSolicitar',
							'name' => 'botonSolicitar',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'allow_in_bindings' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c80d009a89' => array(
					'key' => 'layout_673c80d009a89',
					'name' => 'faq',
					'label' => 'F.A.Q.',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673c41d917d3d',
							'label' => 'Encabezado',
							'name' => 'encabezado',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_673b3b42bac97',
							'label' => 'Acordeón F.A.Q.',
							'name' => 'acordeonFAQ',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Agregar Fila',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_673c421f17d40',
									'label' => 'Pregunta',
									'name' => 'pregunta',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_673b3b42bac97',
								),
								array(
									'key' => 'field_673c422b17d41',
									'label' => 'Respuesta',
									'name' => 'respuesta',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 1,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_673b3b42bac97',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c807f432d6' => array(
					'key' => 'layout_673c807f432d6',
					'name' => 'sliderValoraciones',
					'label' => 'Slider Valoraciones',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673b3ba4bac98',
							'label' => 'Sección Valoraciones',
							'name' => 'seccionValoraciones',
							'aria-label' => '',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'layout_673b3af381d29' => array(
									'key' => 'layout_673b3af381d29',
									'name' => '',
									'label' => '',
									'display' => 'block',
									'sub_fields' => array(
									),
									'min' => '',
									'max' => '',
								),
							),
							'min' => '',
							'max' => '',
							'button_label' => 'Agregar Fila',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c804a13aee' => array(
					'key' => 'layout_673c804a13aee',
					'name' => 'contacto',
					'label' => 'Contacto',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_673b3ba6bac99',
							'label' => 'Encabezado',
							'name' => 'encabezado',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_673c8f6324e74',
							'label' => 'Shortcode Formulario',
							'name' => 'formulario',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_673c805813af0' => array(
					'key' => 'layout_673c805813af0',
					'name' => 'galeriaImagenes',
					'label' => 'Galería de imágenes',
					'display' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_673b3ba7bac9a',
							'label' => 'Galería',
							'name' => 'galeria',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Agregar Fila',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_673c90d32ecbd',
									'label' => 'Imágenes',
									'name' => 'imagenes',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_673b3ba7bac9a',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Agregar Fila',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Contenido general de la página de inicio',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_673c72d09046e',
	'title' => 'Datos',
	'fields' => array(
		array(
			'key' => 'field_673c72d01ccc3',
			'label' => 'Datos',
			'name' => 'datos',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_673c72fd1ccc4',
					'label' => 'Teléfono',
					'name' => 'telefono',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_673c740a4374b',
					'label' => 'Dirección',
					'name' => 'direccion',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'ajustesTema',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Datos del Negocio',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_673b4232a2eb6',
	'title' => 'Elementos Header',
	'fields' => array(
		array(
			'key' => 'field_673b42978d412',
			'label' => 'Mensaje Top Header',
			'name' => 'topHeader',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_673dd68e95800',
					'label' => 'Línea 1',
					'name' => 'topHeaderLine1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_673dd6a595801',
					'label' => 'Línea 2',
					'name' => 'topHeaderLine2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_673b42328d40f',
			'label' => 'Banner Logo',
			'name' => 'bannerLogo',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_673c60eee3585',
					'label' => 'Eslogan',
					'name' => 'eslogan',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_673c60fce3586',
					'label' => 'Botón Contacta',
					'name' => 'botonContacta',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'allow_in_bindings' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-ajustes-de-header',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Contenido del header',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_673c75203f1ff',
	'title' => 'Logos',
	'fields' => array(
		array(
			'key' => 'field_673c752039ac6',
			'label' => 'Logo Corporativo',
			'name' => 'logoCorporativo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_673c754f39ac7',
			'label' => 'Redes Sociales',
			'name' => 'rrss',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Agregar Fila',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_673c75d939ac8',
					'label' => 'Iconos Redes Sociales',
					'name' => 'iconoRS',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'parent_repeater' => 'field_673c754f39ac7',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'ajustesTema',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Logos corporativos, redes sociales',
	'show_in_rest' => 0,
) );
} );



